name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automate-test:
    runs-on: ubuntu-latest

    steps:
    # Download Repo
    - uses: actions/checkout@v3
    
    # Setup Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Install Browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0

    # Setup Gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew

    # Setup Executing Test
    - name: Setup executing test
      run: ./gradlew tesCucumber
      
    #Archive artifact test
    - name: Archive artifact result Test
      uses: actions/upload-artifact@v3.1.3
      if: always()
      with: 
        name: Testing Reports
        path: reports

    # Deploy to Github Page
    - name: Deploy report test to Github Page
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: always()
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports